TYPO3:
  Flow:
    persistence:
      backendOptions:
        dbname: 'news' # adjust to your database name
        user: 'root'         # adjust to your database user
        password: '' # adjust to your database password
        host: 'localhost'    # adjust to your database host
